config/routes.rb
Colchonet::Application.routes.draw do

  resources :rooms
  resources :users

  root :to => 'home#index'

  

end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :description, :location, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bio, :email, :full_name, :location, :password, :password_confirmation

  validates_presence_of :email, :full_name, :location
  validates_length_of :bio, :minimum => 30, :allow_blank => false
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_uniqueness_of :email

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new (params[:user])
    if @user.save
      redirect_to @user,
                  :notice => 'Cadastro criado com sucesso!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user]) 
      redirect_to @user, :notice => 'Cadastro atualizado com sucesso!'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Colcho.net</h1>

<p>
  Escolha uma das ações a seguir:
  <ul>
      <li><%= link_to "Cadastro" , new_user_path %></li>
      <li><%= link_to "Visualizar Quartos" , rooms_path %></li>
    </ul>  
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Pacifico" type="text/css" >
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div id="header-wrap">
      <h1><%= link_to "colcho.net" , root_path %></h1>
      <nav>
        <ul>
          <li><%= link_to "Quartos", rooms_path %></li>
          <li><%= link_to "Cadastro", new_user_path %></li>
        </ul>
      </nav>
    </div>
  </header>

  <div id="content">
    <% if notice.present  %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <% if alert.present  %>
      <p id="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>

  </div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.title %></td>
    <td><%= room.location %></td>
    <td><%= room.description %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>
<%= link_to 'Home', root_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @room.title %>
</p>

<p>
  <b>Location:</b>
  <%= @room.location %>
</p>

<p>
  <b>Description:</b>
  <%= @room.description %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/edit.html.erb
<h1> Editar Perfil </h1>

<%= render 'form' %>

<%= link_to "Voltar", @user %>  

app/views/users/new.html.erb
<h1> Cadastro </h1>

<%= render 'form' %>

<%= link_to "Voltar", root_path %>  
    

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Perfil: <%= @user.full_name %></h2>

<ul>
  <li>Localização: <%= @user.location %></li>
  <li>Bio: <%= @user.bio %></li>
</ul>

<%= link_to 'Editar Perfil', edit_user_path(@user) %>
<%= link_to 'Home', root_path %>